# 注册中心的信息
spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.225:8848
    gateway:
      routes:
        - id: route1  # 测试1
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu  # 满足这个条件就访问 baidu.com
        - id: route2  # 测试2
          uri: https://www.jd.com
          predicates:
            - Query=url,jd
        - id: product_route  # 商品服务
          uri: lb://mall-product
          predicates:
            - Path=/app/product/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: third-route  # 三方服务
          uri: lb://mall-third
          predicates:
            - Path=/app/third/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: member-route  # 会员服务
          uri: lb://mall-member
          predicates:
            - Path=/app/member/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: ware-route  # 库存管理服务
          uri: lb://mall-ware
          predicates:
            - Path=/app/ware/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: login_route  # renren-fast 登录验证码
          uri: lb://renren-fast
          predicates:
            - Path=/app/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /renren-fast/$\{segment}
        - id: mall_msb_host_route  # 前端的首页 mall.msb.com
          uri: lb://mall-product
          predicates:
            - Host=mall.msb.com
        - id: search_msb_host_route  # 搜索跳转首页 search.msb.com
          uri: lb://mall-search
          predicates:
            - Host=search.msb.com
        - id: item_msb_host_route  # 商品详情页面 item.msb.com
          uri: lb://mall-product
          predicates:
            - Host=item.msb.com
        - id: auth_msb_host_route  # 商品详情页面 auth.msb.com
          uri: lb://mall-auth
          predicates:
            - Host=auth.msb.com
        - id: cart_msb_host_route  # 商品详情页面 cart.msb.com
          uri: lb://mall-cart
          predicates:
            - Host=cart.msb.com
        - id: order_msb_host_route  # 商品详情页面 order.msb.com
          uri: lb://mall-order
          predicates:
            - Host=order.msb.com


# 指定注册中心的服务端口
server:
  port: 8070