spring:
  application:
    name: mall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.225:8848
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 192.168.31.225
  session:
    store-type: redis
    redis:
      namespace: spring:session


server:
  port: 40000
  servlet:
    session:
      timeout: 30m