spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.31.225:3306/mall-pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.225:8848
    alicloud:
      access-key: LTAI5tAXhTRSDupN7Mddf465
      secret-key: GrY0ZvKfFTKOjwoPbDsnROyRFP4CV4
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
  session:
    store-type: redis
    redis:
      namespace: spring:session # 前缀

  application:
    name: mall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.31.225
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60000 # 1分钟过期时间
      cache-null-values: true # 缓存穿透(绕过) 处理

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)


server:
  port: 8040
  servlet:
    session:
      timeout: 30m # session超时30分钟