spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.225:8848
  application:
    name: mall-search
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  session:
    store-type: redis
    redis:
      namespace: spring:session
  redis:
    port: 6379
    host: 192.168.31.225

server:
  port: 8091
  servlet:
    session:
      timeout: 30m # session超时30分钟