spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.31.225:3306/mall-oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.225:8848
  application:
    name: mall-order
  session:
    store-type: redis
    redis:
      namespace: spring:session
  redis:
    host: 192.168.31.225
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增

server:
  port: 8030
  servlet:
    session:
      timeout: 30m


user:
  userName: application.zhangsan
  age: 18

